version: '3.8'

services:
  # Layanan Frontend (Vue.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy

  # Layanan Backend (Go API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: ":8080"
      JWT_SECRET_KEY: "kunci_rahasia_super_aman_untuk_docker"
      DATABASE_URL: "postgres://postgres:arda123@db:5432/LoginDB?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/api/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Layanan Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arda123
      POSTGRES_DB: LoginDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LoginDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: